version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sleep", "infinity"]
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
