// -- AUTH REQUESTS --

// Sign up request
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Test",
	"email": "user@gmail.com",
	"password": "password",
	"role": "CUSTOMER"
}

// Log in request
POST http://localhost:3000/api/auth/log-in
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "password"
}

// Log out request
POST http://localhost:3000/api/auth/log-out
Content-Type: application/json
Cookie: token=YOUR_TOKEN
