// -- BOOK REQUESTS

// Get all books request
GET http://localhost:3000/api/books
Content-Type: application/json

// Get book by title request
GET http://localhost:3000/api/books?title=TITLE_BOOK_HERE
Content-Type: application/json

// Get book by genre request
GET http://localhost:3000/api/books?genreId=ID_GENRE_HERE
Content-Type: application/json

// Get book by page and size request
GET http://localhost:3000/api/books?page=PAGE_HERE&size=SIZE_HERE
Content-Type: application/json

// Get single book request
GET http://localhost:3000/api/books/:id
Content-Type: application/json
